server:
  servlet:
    context-path: /user
  port: 8080
#连接信息配置
spring:
  datasource:
    platform: h2 ##表明使用的数据库平台是h2
    #schema: classpath:h2/schema.sql #初始化数据库：指定生成数据库的schema文件位置（建表语句）
        #采用本地或远程方式，第一次启动项目初始化完成生成.mv.db文件后，需要注释掉data
        #否则在一个db文件初始化两次，插入相同主键的数据，项目启动不来，或者直接删除db文件，重新生成
#    data: classpath:h2/data.sql #指定插入数据库语句的脚本位置（插入记录语句）
             #数据库地址
    #url: jdbc:h2:~/test #本地嵌入式连接，只能有一个客户端连接
    #url: jdbc:h2:~/test;AUTO_SERVER=TRUE #本地嵌入式连接，可以和浏览器一起访问。
    #url: jdbc:h2:tcp://localhost/~/test ##连接位于用户目录下的test数据库
    url: jdbc:h2:mem:test #内存模式连接
    driver-class-name: org.h2.Driver #数据库驱动
    username: user1 #数据库用户名，没有就创建，或者使用默认就有sa用户，没有密码
    password: user1 #数据库密码
#h2配置
  h2:
    console:  #h2 web console设置
      settings:
        web-allow-others: true #进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
      path: /h2 #可以通过YOUR_URL/h2访问h2 web console YOUR_URL是你程序的访问URl。默认是h2-console
      enabled: true #进行该配置，程序开启时就会启动h2 web consloe。
#jpa配置
  jpa:
    hibernate:
      ddl-auto: update #JPA自动创建，存在就是更新
    show-sql: true #启用SQL语句的日志记录
    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect

##mysql配置
#spring:
#  datasource:
#    url: jdbc:mysql://12.1.1.30:3306/mvptest?useSSL=FALSE&serverTimezone=UTC&autoReconnect=yes&useUnicode=yes&characterEncoding=UTF-8
#    river-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456

#spring data redis
  redis:
    host: 127.0.0.1
    port: 6379
#    database: 6
#    password: 123456


